name: Sync chatgpt/chatgpt-widescreen/ to (adamlui/chatgpt-widescreen/greasemonkey/ && adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/), then /greasemonkey/_locales/ to adamlui/chatgpt-apps/chatgpt-widescreen/(chrome|edge|opera)/extension/_locales/

on:
  push:
    branches: [ master, main ]
    paths:
      - 'chatgpt/chatgpt-widescreen/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'kudo-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync chatgpt/chatgpt-widescreen/ to adamlui/chatgpt-widescreen/greasemonkey/
        run: rsync -avhr --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/ ${{ github.workspace }}/adamlui/chatgpt-widescreen/greasemonkey/

      - name: Sync chatgpt/chatgpt-widescreen/ to adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/
        run: rsync -avhr --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/ ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/

      - name: Sync /greasemonkey/_locales/ to adamlui/chatgpt-apps/chatgpt-widescreen/(chrome|edge|opera)/extension/_locales/
        run: |
          for browser in chrome edge opera
          do
            rsync -avhr --delete "${{ github.workspace }}/adamlui/chatgpt-widescreen/greasemonkey/_locales/" "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/$browser/extension/_locales/"
          done

      - name: Push to adamlui/chatgpt-widescreen
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: '**'
          repository: adamlui/chatgpt-widescreen

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: 'chatgpt-widescreen/**'
          repository: adamlui/chatgpt-apps
