name: Sync chatgpt/chatgpt-auto-refresh/ to (adamlui/chatgpt-auto-refresh/greasemonkey/ && adamlui/chatgpt-apps/chatgpt-auto-refresh/greasemonkey/)

on:
  push:
    branches: [ master, main ]
    paths:
      - 'chatgpt/chatgpt-auto-refresh/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'kudo-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-auto-refresh
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-auto-refresh
          path: adamlui/chatgpt-auto-refresh

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync docs to adamlui/chatgpt-auto-refresh/docs/ && adamlui/chatgpt-apps/chatgpt-auto-refresh/docs/
        run: cp -r -f -v ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-refresh/docs ${{ github.workspace }}/adamlui/chatgpt-auto-refresh/ && cp -r -f -v ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-refresh/docs ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-refresh/

      - name: Sync chatgpt/chatgpt-auto-refresh/ to adamlui/chatgpt-auto-refresh/greasemonkey/
        run: rsync -avhr --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-refresh/ ${{ github.workspace }}/adamlui/chatgpt-auto-refresh/greasemonkey/

      - name: Sync chatgpt/chatgpt-auto-refresh/ to adamlui/chatgpt-apps/chatgpt-auto-refresh/greasemonkey/
        run: rsync -avhr --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-refresh/ ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-refresh/greasemonkey/

      - name: Push to adamlui/chatgpt-auto-refresh
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: '**'
          repository: adamlui/chatgpt-auto-refresh

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]'
          file_pattern: 'chatgpt-auto-refresh/**'
          repository: adamlui/chatgpt-apps