name: Sync github/github-widescreen/ to adamlui/github-widescreen/greasemonkey/

on:
  push:
    branches: master
    paths: github/github-widescreen/**

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/github-widescreen
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/github-widescreen
          path: adamlui/github-widescreen

      - name: Sync github/github-widescreen/docs/** to adamlui/github-widescreen/docs/**
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/github/github-widescreen/docs \
            ${{ github.workspace }}/adamlui/github-widescreen/

      - name: Sync github/github-widescreen/ to adamlui/github-widescreen/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/github/github-widescreen/ \
            ${{ github.workspace }}/adamlui/github-widescreen/greasemonkey/

      - name: Push to adamlui/github-widescreen
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]"
          file_pattern: "**"
          repository: adamlui/github-widescreen
