name: Sync chatgpt/chatgpt-auto-talk/ to (adamlui/chatgpt-auto-talk/greasemonkey/ && adamlui/chatgpt-apps/chatgpt-auto-talk/greasemonkey/)

on:
  push:
    branches: [master]
    paths: [chatgpt/chatgpt-auto-talk/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-auto-talk
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-auto-talk
          path: adamlui/chatgpt-auto-talk

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync docs to adamlui/chatgpt-auto-talk/docs/ && adamlui/chatgpt-apps/chatgpt-auto-talk/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-talk/docs \
            ${{ github.workspace }}/adamlui/chatgpt-auto-talk/
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-talk/docs \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-talk/

      - name: Sync chatgpt/chatgpt-auto-talk/ to adamlui/chatgpt-auto-talk/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-talk/ \
            ${{ github.workspace }}/adamlui/chatgpt-auto-talk/greasemonkey/

      - name: Sync chatgpt/chatgpt-auto-talk/ to adamlui/chatgpt-apps/chatgpt-auto-talk/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-talk/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-talk/greasemonkey/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG=$(echo "$COMMIT_MSG" | sed 's/`/\`/g')" >> $GITHUB_ENV

      - name: Push changes to adamlui/chatgpt-auto-talk
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-auto-talk
          git add .
          git commit -n -m "ESCAPED_MSG ↞ [auto-sync from \`adamlui/userscripts\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git add .
          git commit -n -m "ESCAPED_MSG ↞ [auto-sync from \`adamlui/userscripts/chatgpt/chatgpt-auto-talk\`]" || true
          git push
