name: Sync chatgpt/amazongpt/ to (KudoAI/amazongpt/greasemonkey/ && adamlui/ai-apps/amazongpt/greasemonkey/)

on:
  push:
    branches: [master]
    paths: [chatgpt/amazongpt/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout KudoAI/amazongpt
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/amazongpt
          path: KudoAI/amazongpt

      - name: Checkout adamlui/ai-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/ai-apps
          path: adamlui/ai-apps

      - name: Sync docs to KudoAI/amazongpt/docs/ && adamlui/ai-apps/amazongpt/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/amazongpt/docs \
            ${{ github.workspace }}/KudoAI/amazongpt/
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/amazongpt/docs \
            ${{ github.workspace }}/adamlui/ai-apps/amazongpt/

      - name: Sync chatgpt/amazongpt/ to KudoAI/amazongpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/amazongpt/ \
            ${{ github.workspace }}/KudoAI/amazongpt/greasemonkey/

      - name: Sync chatgpt/amazongpt/ to adamlui/ai-apps/amazongpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/amazongpt/ \
            ${{ github.workspace }}/adamlui/ai-apps/amazongpt/greasemonkey/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to KudoAI/amazongpt
        run: |
          cd ${{ github.workspace }}/KudoAI/amazongpt
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/userscripts\`]" || true
          git push

      - name: Push changes to adamlui/ai-apps
        run: |
          cd ${{ github.workspace }}/adamlui/ai-apps
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/userscripts/chatgpt/amazongpt\`]" || true
          git push
