name: Sync chatgpt/duckduckgpt/ to (KudoAI/duckduckgpt/greasemonkey/ && adamlui/chatgpt-apps/duckduckgpt/greasemonkey/)

on:
  push:
    branches: [master]
    paths: [chatgpt/duckduckgpt/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout KudoAI/duckduckgpt
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/duckduckgpt
          path: KudoAI/duckduckgpt

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync docs to KudoAI/duckduckgpt/docs/ && adamlui/chatgpt-apps/duckduckgpt/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/docs \
            ${{ github.workspace }}/KudoAI/duckduckgpt/
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/docs \
            ${{ github.workspace }}/adamlui/chatgpt-apps/duckduckgpt/

      - name: Sync chatgpt/duckduckgpt/ to KudoAI/duckduckgpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/ \
            ${{ github.workspace }}/KudoAI/duckduckgpt/greasemonkey/

      - name: Sync chatgpt/duckduckgpt/ to adamlui/chatgpt-apps/duckduckgpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/duckduckgpt/greasemonkey/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to KudoAI/duckduckgpt
        run: |
          cd ${{ github.workspace }}/KudoAI/duckduckgpt
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/userscripts\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/userscripts/chatgpt/duckduckgpt\`]" || true
          git push
