name: Sync chatgpt/autoclear-chatgpt-history/ to (adamlui/autoclear-chatgpt-history/greasemonkey/ && adamlui/chatgpt-apps/autoclear-chatgpt-history/greasemonkey/)

on:
  push:
    branches: [master]
    paths: [chatgpt/autoclear-chatgpt-history/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/autoclear-chatgpt-history
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/autoclear-chatgpt-history
          path: adamlui/autoclear-chatgpt-history

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync docs to adamlui/autoclear-chatgpt-history/docs/ && adamlui/chatgpt-apps/autoclear-chatgpt-history/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/docs \
            ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/docs \
            ${{ github.workspace }}/adamlui/chatgpt-apps/autoclear-chatgpt-history/

      - name: Sync chatgpt/autoclear-chatgpt-history/ to adamlui/autoclear-chatgpt-history/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/ \
            ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/greasemonkey/

      - name: Sync chatgpt/autoclear-chatgpt-history/ to adamlui/chatgpt-apps/autoclear-chatgpt-history/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/autoclear-chatgpt-history/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/autoclear-chatgpt-history/greasemonkey/

      - name: Push to adamlui/autoclear-chatgpt-history
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]"
          file_pattern: "**"
          repository: adamlui/autoclear-chatgpt-history

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts/chatgpt/autoclear-chatgpt-history`]"
          file_pattern: "autoclear-chatgpt-history/**"
          repository: adamlui/chatgpt-apps
