name: Sync chatgpt/bravegpt/ to (KudoAI/bravegpt/greasemonkey/ && adamlui/chatgpt-apps/bravegpt/greasemonkey/)

on:
  push:
    branches: [master]
    paths: [chatgpt/bravegpt/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout KudoAI/bravegpt
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/bravegpt
          path: KudoAI/bravegpt

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync docs to KudoAI/bravegpt/docs/ && adamlui/chatgpt-apps/bravegpt/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/docs \
            ${{ github.workspace }}/KudoAI/bravegpt/
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/docs \
            ${{ github.workspace }}/adamlui/chatgpt-apps/bravegpt/

      - name: Sync chatgpt/bravegpt/ to KudoAI/bravegpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/ \
            ${{ github.workspace }}/KudoAI/bravegpt/greasemonkey/

      - name: Sync chatgpt/bravegpt/ to adamlui/chatgpt-apps/bravegpt/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/bravegpt/greasemonkey/

      - name: Push changes to KudoAI/bravegpt
        run: |
          cd ${{ github.workspace }}/KudoAI/bravegpt
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git add .
          git commit -n -m "$(echo '${{ github.event.head_commit.message }}' | sed 's/`/\`/g') ↞ [auto-sync from \`adamlui/userscripts\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git add .
          git commit -n -m "$(echo '${{ github.event.head_commit.message }}' | sed 's/`/\`/g') ↞ [auto-sync from \`adamlui/userscripts/chatgpt/bravegpt\`]" || true
          git push
