name: Sync chatgpt/chatgpt-widescreen/ to (adamlui/chatgpt-widescreen/greasemonkey/ && adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/), then /greasemonkey/_locales/ to adamlui/chatgpt-apps/chatgpt-widescreen/(chrome|edge|opera)/extension/_locales/

on:
  push:
    branches: [master]
    paths: [chatgpt/chatgpt-widescreen/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync chatgpt/chatgpt-widescreen/ to adamlui/chatgpt-widescreen/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/ \
            ${{ github.workspace }}/adamlui/chatgpt-widescreen/greasemonkey/

      - name: Sync chatgpt/chatgpt-widescreen/ to adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/

      - name: Sync /greasemonkey/_locales/ to adamlui/chatgpt-apps/chatgpt-widescreen/(chrome|edge|opera)/extension/_locales/
        run: |
          for browser in chrome edge opera
          do
            rsync -avhr --delete \
              "${{ github.workspace }}/adamlui/chatgpt-widescreen/greasemonkey/_locales/" \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/$browser/extension/_locales/"
          done

      - name: Push changes to adamlui/chatgpt-widescreen
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-widescreen
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git add .
          git commit -n -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git add .
          git commit -n -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts/chatgpt/chatgpt-widescreen`]" || true
          git push
