name: Sync github/github-star-history/ to adamlui/github-star-history/greasemonkey/

on:
  push:
    branches: [master]
    paths: [github/github-star-history/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/github-star-history
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/github-star-history
          path: adamlui/github-star-history

      - name: Sync github/github-star-history/docs/** to adamlui/github-star-history/docs/**
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/github/github-star-history/docs \
            ${{ github.workspace }}/adamlui/github-star-history/

      - name: Sync github/github-star-history/ to adamlui/github-star-history/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/github/github-star-history/ \
            ${{ github.workspace }}/adamlui/github-star-history/greasemonkey/

      - name: Push changes to adamlui/github-star-history
        run: |
          cd ${{ github.workspace }}/adamlui/github-star-history
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git add .
          git commit -n -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]" || true
          git push
