name: Sync chatgpt/chatgpt-auto-refresh/ to (adamlui/chatgpt-auto-refresh/greasemonkey/ && adamlui/chatgpt-apps/chatgpt-auto-refresh/greasemonkey/)

on:
  push:
    branches: [master]
    paths: [chatgpt/chatgpt-auto-refresh/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-auto-refresh
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-auto-refresh
          path: adamlui/chatgpt-auto-refresh

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync docs to adamlui/chatgpt-auto-refresh/docs/ && adamlui/chatgpt-apps/chatgpt-auto-refresh/docs/
        run: |
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-refresh/docs \
            ${{ github.workspace }}/adamlui/chatgpt-auto-refresh/
          cp -r -f -v \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-refresh/docs \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-refresh/

      - name: Sync chatgpt/chatgpt-auto-refresh/ to adamlui/chatgpt-auto-refresh/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-refresh/ \
            ${{ github.workspace }}/adamlui/chatgpt-auto-refresh/greasemonkey/

      - name: Sync chatgpt/chatgpt-auto-refresh/ to adamlui/chatgpt-apps/chatgpt-auto-refresh/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-refresh/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-refresh/greasemonkey/

      - name: Push changes to adamlui/chatgpt-auto-refresh
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-auto-refresh
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git add .
          git commit -n -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git add .
          git commit -n -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/userscripts/chatgpt/chatgpt-auto-refresh`]" || true
          git push
