name: Sync chatgpt/chatgpt-widescreen/ to (adamlui/chatgpt-widescreen/greasemonkey/ && adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/), then /greasemonkey/_locales/ to adamlui/chatgpt-apps/chatgpt-widescreen/(chrome|edge|opera)/extension/_locales/

on:
  push:
    branches: [master]
    paths: [chatgpt/chatgpt-widescreen/**]

jobs:
  build:
    if: (github.repository == 'adamlui/userscripts') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Sync chatgpt/chatgpt-widescreen/ to adamlui/chatgpt-widescreen/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/ \
            ${{ github.workspace }}/adamlui/chatgpt-widescreen/greasemonkey/

      - name: Sync chatgpt/chatgpt-widescreen/ to adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/ \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/

      - name: Sync /greasemonkey/_locales/ to adamlui/chatgpt-apps/chatgpt-widescreen/(chrome|edge|opera)/extension/_locales/
        run: |
          for browser in chrome edge opera
          do
            rsync -avhr --delete \
              "${{ github.workspace }}/adamlui/chatgpt-widescreen/greasemonkey/_locales/" \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/$browser/extension/_locales/"
          done

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to adamlui/chatgpt-widescreen
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-widescreen
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/userscripts\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/userscripts/chatgpt/chatgpt-widescreen\`]" || true
          git push
